site_name: Payjoin Integration Tracker

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: pink
  features:
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Integrations: integrations.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
